from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class MessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class AgentMessage(BaseModel):
    role: MessageRole
    content: str
    name: str | None = None
    tool_call_id: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class VerificationStatus(StrEnum):
    UNVERIFIED = "unverified"
    PROVENANCE_VALIDATED = "provenance_validated"
    HUMAN_REVIEWED = "human_reviewed"
    CONFLICTED = "conflicted"
    STALE = "stale"


class BoundingBox(BaseModel):
    page: int
    x1: float
    y1: float
    x2: float
    y2: float


class ProvenanceChain(BaseModel):
    """
    Detailed traceability from a result back to the original physical source.
    Maps: Graph Node/Edge -> Evidence Region -> Chunk -> Page -> Revision -> Original Document
    """
    node_id: str | None = None
    relationship_id: str | None = None
    evidence_region_id: str
    chunk_id: str | None = None
    document_id: str
    document_version: int
    page_number: str | None = None
    locator: str | None = None
    bounding_box: BoundingBox | None = None
    sha256: str
    source_filename: str
    storage_key: str


class EvidenceSource(BaseModel):
    text_excerpt: str
    provenance: ProvenanceChain
    relevance_score: float = Field(ge=0.0, le=1.0)
    confidence_score: float = Field(ge=0.0, le=1.0)
    verification_status: VerificationStatus = VerificationStatus.UNVERIFIED
    metadata: dict[str, Any] = Field(default_factory=dict)


class ClaimSupportStatus(StrEnum):
    SUPPORTED = "supported"
    REFUTED = "refuted"
    PARTIALLY_SUPPORTED = "partially_supported"
    UNCERTAIN = "uncertain"
    NO_EVIDENCE = "no_evidence"


class GroundedClaim(BaseModel):
    claim_id: str
    text: str
    status: ClaimSupportStatus
    sources: list[EvidenceSource] = Field(default_factory=list)
    reasoning: str | None = None


class GroundedRelationship(BaseModel):
    """
    A graph relationship that has been verified against physical evidence.
    """
    source_id: str
    target_id: str
    relationship_type: str
    evidence: EvidenceSource
    confidence: float


class RecommendedAction(BaseModel):
    action_id: str
    type: str  # TEST, INSPECTION, REPAIR, MONITOR, PROCEDURE_UPDATE, TRAINING
    description: str
    priority: str = "medium"  # low, medium, high, critical
    reasoning: str
    linked_claim_ids: list[str] = Field(default_factory=list)


class Contradiction(BaseModel):
    contradiction_id: str
    summary: str
    description: str
    involved_evidence_ids: list[str]
    severity: str = "high"


class QueryIntent(StrEnum):
    ASSET_INFO = "asset_info"
    RCA = "rca"
    COMPLIANCE = "compliance"
    LESSONS_LEARNED = "lessons_learned"
    GENERAL = "general"


class RetrievalStrategy(StrEnum):
    GRAPH_TRAVERSAL = "graph_traversal"
    VECTOR_SEARCH = "vector_search"
    METADATA_FILTER = "metadata_filter"
    SQL_QUERY = "sql_query"
    LEXICAL_SEARCH = "lexical_search"
    RERANKING = "reranking"


class RetrievalPlan(BaseModel):
    intent: QueryIntent
    strategies: list[RetrievalStrategy]
    target_entities: list[str] = Field(default_factory=list)
    filters: dict[str, Any] = Field(default_factory=dict)
    reasoning: str


class ResolvedEntity(BaseModel):
    original_text: str
    entity_id: str
    entity_type: str
    confidence: float
    canonical_name: str
    aliases: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class EvidenceBundle(BaseModel):
    query_id: str
    intent: QueryIntent
    resolved_entities: list[ResolvedEntity] = Field(default_factory=list)
    verified_evidence: list[EvidenceSource] = Field(default_factory=list)
    grounded_relationships: list[GroundedRelationship] = Field(default_factory=list)
    raw_graph_data: dict[str, Any] = Field(default_factory=dict)
    raw_vector_data: list[dict[str, Any]] = Field(default_factory=list)
    contradictions: list[Contradiction] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
    retrieved_at: datetime = Field(default_factory=datetime.utcnow)


class AgentResponse(BaseModel):
    """
    The final grounded report generated by Mnemos.
    """
    answer: str
    confidence_score: float = Field(ge=0.0, le=1.0)
    claims: list[GroundedClaim] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    contradictions: list[Contradiction] = Field(default_factory=list)
    recommended_actions: list[RecommendedAction] = Field(default_factory=list)
    graph_paths: list[list[str]] = Field(default_factory=list, description="KG paths supporting the answer")
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(from_attributes=True)
